rvm: 2.2.3
script:
- bundle exec bin/rake db:create
- bundle exec bin/rake db:migrate
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: m84tyZ6jtVQtZxTHFLjA4WYAclxI1C4GxX9FjN+hY2MxVzM+NEIPBVJBjlR6BEOMXXF++B/O/Ym5xuX29UPlPM0BiHwDBYpYTnMCMvSjPpj8qkl/Ti16E6RZRpA67/LiEawII915UhJdtHnRTlzjPHN0KY38N2d9RZgyXW5g9EVEWi6Z4PsgJSiUO1GAHvWMROVYTtFvj8ftuXzv25rlwC3eug0BHDi2pS9vC/uvKbw8Ogc8OW1VUWWTmwXKVwEph2Z+YRlU9HDOv3VZMVcNiXjE+crvkuXbR5IAAq/fU3sK04BsU7IcEZ3p+WfpqP/KydWfJVeKuhAPfpEeXtnH1btA0c1AgozlD7kGPaMl2n39rKVBX6B4TU0LgM7XqDI0xkCqtz73g+/hLXB71u76gmd+3CgSHbsz1mH2rnYGyJTpfWwHEi0u9xozuZD/JtAjHS3b8hw4j5tHeZ7/X1MOOU+S9/x1EfUm+NwOq6lov30rRJ7rOOFT5lkV7850q02XQDY6ahfgULF1NW/pxn4Z+hL6+fPFIfMvZ4LkPtEWKxfUaS2aYjHqNl6Fq0Ny/2NLaTJPEncvtV6kvnWuP4/YwVA6xRc9P5YT5M0z1fX8l9Ots2+S2p0sHIRHzTL5Tz1E502NgWUUU9vmY85BymyGVO2B6Qwdw85MhAEzgn9r3Mg=
  app: se23-local-guide
  on:
    repo: emmabeynon/twitter_local_guide
